-- ============================================================================
-- TUNA KAKA TEA STALL: COMPLETE SUPABASE POSTGRESQL SCHEMA
-- ============================================================================
-- Instructions:
-- 1. Log in to your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Select your project.
-- 3. In the left navigation, click "SQL Editor" -> "+ New query".
-- 4. Copy & paste this entire SQL script into the editor.
-- 5. Click "Run" (or Ctrl + Enter).
-- 6. Go to Project Settings -> API to copy your "Project URL" and "anon public" key.
-- ============================================================================

-- Enable pgcrypto extension if needed for UUIDs or cryptographic functions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ----------------------------------------------------------------------------
-- 1. CUSTOMERS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT PRIMARY KEY,
    custom_id TEXT,
    name TEXT NOT NULL,
    mobile TEXT,
    address TEXT,
    notes TEXT,
    created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

CREATE INDEX IF NOT EXISTS idx_customers_name ON public.customers(name);
CREATE INDEX IF NOT EXISTS idx_customers_mobile ON public.customers(mobile);

-- ----------------------------------------------------------------------------
-- 2. MENU ITEMS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    rate NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_menu_category ON public.menu_items(category);

-- ----------------------------------------------------------------------------
-- 3. ORDERS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT PRIMARY KEY,
    order_number TEXT,
    customer_id BIGINT,
    customer_name TEXT,
    customer_mobile TEXT,
    order_date BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    paid_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    balance_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    payment_method TEXT DEFAULT 'Cash',
    status TEXT DEFAULT 'COMPLETED',
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON public.orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_date ON public.orders(order_date);

-- ----------------------------------------------------------------------------
-- 4. ORDER ITEMS TABLE (Detailed Line Items per Order)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    item_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    rate NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);

-- ----------------------------------------------------------------------------
-- 5. PAYMENTS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    customer_name TEXT,
    order_id BIGINT,
    payment_date BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    payment_method TEXT DEFAULT 'Cash',
    notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_payments_customer_id ON public.payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON public.payments(payment_date);

-- ----------------------------------------------------------------------------
-- 6. CUSTOMER LEDGER TABLE (Credit / Jama & Debit / Udhar Khata)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.customer_ledger (
    id BIGINT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    date BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    transaction_type TEXT NOT NULL, -- 'DEBIT' (purchase) or 'CREDIT' (payment)
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    title TEXT,
    details TEXT,
    payment_mode TEXT,
    reference_no TEXT
);

CREATE INDEX IF NOT EXISTS idx_ledger_customer_id ON public.customer_ledger(customer_id);
CREATE INDEX IF NOT EXISTS idx_ledger_date ON public.customer_ledger(date);

-- ----------------------------------------------------------------------------
-- 7. INVENTORY ITEMS TABLE (Raw Materials: Milk, Tea Leaves, Sugar, etc.)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    unit TEXT DEFAULT 'kg',
    current_stock NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    low_stock_threshold NUMERIC(10, 2) NOT NULL DEFAULT 2.00,
    cost_per_unit NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    last_updated BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

-- ----------------------------------------------------------------------------
-- 8. INVENTORY CONSUMPTION LOGS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.inventory_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT,
    item_name TEXT NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    unit TEXT,
    date BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    type TEXT, -- 'CONSUMPTION' or 'RESTOCK'
    remaining_stock_after NUMERIC(10, 2),
    notes TEXT
);

-- ----------------------------------------------------------------------------
-- 9. ROW LEVEL SECURITY (RLS) POLICIES FOR SUPABASE CLIENT API
-- ----------------------------------------------------------------------------
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_logs ENABLE ROW LEVEL SECURITY;

-- Allow anon public read and write access for mobile client sync
DROP POLICY IF EXISTS "Allow anon all on customers" ON public.customers;
CREATE POLICY "Allow anon all on customers" ON public.customers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on menu_items" ON public.menu_items;
CREATE POLICY "Allow anon all on menu_items" ON public.menu_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on orders" ON public.orders;
CREATE POLICY "Allow anon all on orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on order_items" ON public.order_items;
CREATE POLICY "Allow anon all on order_items" ON public.order_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on payments" ON public.payments;
CREATE POLICY "Allow anon all on payments" ON public.payments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on customer_ledger" ON public.customer_ledger;
CREATE POLICY "Allow anon all on customer_ledger" ON public.customer_ledger FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on inventory_items" ON public.inventory_items;
CREATE POLICY "Allow anon all on inventory_items" ON public.inventory_items FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on inventory_logs" ON public.inventory_logs;
CREATE POLICY "Allow anon all on inventory_logs" ON public.inventory_logs FOR ALL USING (true) WITH CHECK (true);

-- ----------------------------------------------------------------------------
-- 10. INITIAL DEFAULT MENU ITEMS & RAW MATERIALS (OPTIONAL SEED DATA)
-- ----------------------------------------------------------------------------
INSERT INTO public.menu_items (id, name, category, rate, is_active)
VALUES
    (1, 'Tea (Cutting)', 'Tea', 10.00, true),
    (2, 'Special Masala Tea', 'Tea', 20.00, true),
    (3, 'Milk Tea', 'Tea', 15.00, true),
    (4, 'Black Tea / Lemon Tea', 'Tea', 12.00, true),
    (5, 'Hot Coffee', 'Coffee', 25.00, true),
    (6, 'Cold Coffee', 'Coffee', 35.00, true),
    (7, 'Water Bottle (500ml)', 'Beverage', 10.00, true),
    (8, 'Water Bottle (1L)', 'Beverage', 20.00, true),
    (9, 'Cold Drink', 'Beverage', 20.00, true),
    (10, 'Samosa (Single)', 'Snacks', 15.00, true),
    (11, 'Pakoda Plate', 'Snacks', 30.00, true),
    (12, 'Bun Maska', 'Snacks', 25.00, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.inventory_items (id, name, unit, current_stock, low_stock_threshold, cost_per_unit, last_updated)
VALUES
    (1, 'Fresh Milk', 'Liters', 20.0, 5.0, 60.0, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT),
    (2, 'Assam Tea Leaves', 'kg', 5.0, 1.5, 320.0, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT),
    (3, 'Refined Sugar', 'kg', 15.0, 3.0, 42.0, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT),
    (4, 'Chai Masala Powder', 'grams', 500.0, 100.0, 1.2, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT),
    (5, 'Fresh Ginger (Adrak)', 'kg', 2.0, 0.5, 90.0, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT),
    (6, 'Paper Cups (100ml)', 'pieces', 300.0, 50.0, 0.5, (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT)
ON CONFLICT (id) DO NOTHING;
